#!/bin/sh
app="first"
branch=$(git rev-parse --symbolic --abbrev-ref $1)

mkdir -p /root/apps/${app}
git --work-tree="/root/apps/${app}" checkout -f ${branch}
cd /root/apps/${app}

# Install dependencies
npm install

# Run server
make server-production
