#!/bin/sh
app="first"
branch=$(git rev-parse --symbolic --abbrev-ref $1)

echo '--------------'
echo ${branch}
echo '-------------'

mkdir -p /root/apps/${app}
git --work-tree="/root/apps/${app}" checkout -f ${branch}

# Run server
make server-production
